name: A

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  a:
    runs-on: ubuntu-latest
    steps:

    - name: Release Dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: trigger-b
