name: checkout

on:
  workflow_dispatch:


jobs:
  b:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          repository: ${{ vars.AssetsRepo }}
          path: Assets

      - name: list
        run: ls -la Assets
