name: checkout

on:
  workflow_dispatch:


jobs:
  b:
    runs-on: ubuntu-latest
    steps:

      - name: Check if AssetsRepo is set
        run: |
          if [ -z "${{ vars.AssetsRepo }}" ]; then
            echo "Error: AssetsRepo is not set"
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          repository: ${{ vars.AssetsRepo }}
          path: Assets

      - name: list
        run: ls -la Assets
