name: B

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-b]

jobs:
  b:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4


    - name: Get current date
      id: date
      run: echo "tag=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.tag }}
        name: Release ${{ env.tag }}
        body: |
          - v${{ env.tag }} complete update
        draft: false
        prerelease: true

