
name: test

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:

      - name: Check changes
        id: final_check
        run: |
          if [[ ! -f file-diff.txt || ! -s file-diff.txt ]]; then
            gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
            gh run watch ${{ github.run_id }} --repo ${{ github.repository }}
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload diff file if changed
        uses: actions/upload-artifact@v4
        with:
          name: file-diff
          path: file-diff.txt

      - name: Setup uv
        run: echo A

